"""empty message

Revision ID: c02e9afd9bc7
Revises: 
Create Date: 2025-05-19 18:07:59.450950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02e9afd9bc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('certificate', sa.String(length=10), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('metascore', sa.Float(), nullable=True),
    sa.Column('director', sa.String(length=100), nullable=True),
    sa.Column('cast', sa.String(length=500), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('review_title', sa.String(length=200), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
